import { CustomerRulesConfigAPIResponseType } from '../types';

export const customerRulesConfigMock: CustomerRulesConfigAPIResponseType = [
  {
    name: 'Customer',
    rules: {
      'qubik.customer.active_last_2_weeks': {
        display_name: 'Active L2W',
        supported_comparator: ['=', '!='],
        supported_type: 'bool',
        values: [],
        section: 'Customer',
      },
      'qubik.customer.guest': {
        display_name: 'Guest',
        supported_comparator: ['=', '!='],
        supported_type: 'bool',
        values: [],
        section: 'Customer',
      },
      'qubik.customer.subscriber_status': {
        display_name: 'Subscriber Status',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Customer',
      },
    },
  },
  {
    name: 'Marketing Tech',
    rules: {
      'qubik.mktech.customer.is_most_recent_account': {
        display_name: 'Is Most Recent Account',
        supported_comparator: ['=', '!='],
        supported_type: 'bool',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.loyalty.next_best_action': {
        display_name: 'Customer Loyalty Next Best Action',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.loyalty.status': {
        display_name: 'Loyalty Status',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.propensity_to_order': {
        display_name: 'Propensity To Order',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.returning_probability': {
        display_name: 'Customer Returning Probability',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.segment.discount_group_dh_last_6_months': {
        display_name: 'Discount Group DH L6M',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.segment.discount_group_partner_last_6_months': {
        display_name: 'Discount Group Partner L6M',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.segment.frequency_group_last_6_months': {
        display_name: 'Frequency Group L6M',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.segment.monetary_group_last_6_months': {
        display_name: 'Monetary Group L6M',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.segment.order_variety_group_last_6_months': {
        display_name: 'Order Variety Group L6M',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.customer.times_reactivated': {
        display_name: 'Times Reactivated',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.order_attributes.last_failed_order_failure_owner': {
        display_name: 'Monetary Group L6M',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.order_attributes.last_vendor.kill_category': {
        display_name: 'Last Vendor - Kill Category',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
      'qubik.mktech.order_attributes.last_vendor.vendor_id': {
        display_name: 'Last Vendor - Vendor ID',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Marketing Tech',
      },
    },
  },
  {
    name: 'Monetary Attributes',
    rules: {
      'qubik.monetary_attributes.currency': {
        display_name: 'Currency',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Monetary Attributes',
      },
      'qubik.monetary_attributes.total_basket_value': {
        display_name: 'Total Basket Value',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Monetary Attributes',
      },
      'qubik.monetary_attributes.total_basket_value_12_weeks': {
        display_name: 'Total Basket Value L12W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Monetary Attributes',
      },
      'qubik.monetary_attributes.total_customer_spent': {
        display_name: 'Total Customer Spent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Monetary Attributes',
      },
      'qubik.monetary_attributes.total_customer_spent_last_12_weeks': {
        display_name: 'Total Customer Spent L12W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Monetary Attributes',
      },
      'qubik.monetary_attributes.total_dh_profit': {
        display_name: 'Total DH Profit',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Monetary Attributes',
      },
      'qubik.monetary_attributes.total_dh_profit_last_12_weeks': {
        display_name: 'Total DH Profit L12W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Monetary Attributes',
      },
      'qubik.monetary_attributes.total_dh_revenue': {
        display_name: 'Total DH Revenue',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Monetary Attributes',
      },
      'qubik.monetary_attributes.total_dh_revenue_last_12_weeks': {
        display_name: 'Total DH Revenue L12W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Monetary Attributes',
      },
    },
  },
  {
    name: 'Order Attributes',
    rules: {
      'qubik.order_attributes.avg_ordered_vendors_rating_last_4_weeks': {
        display_name: 'Average Ordered Vendors Rating L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.first_order_timestamp': {
        display_name: 'First Order Timestamp',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'time',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.group_order_rate': {
        display_name: 'Group Order Rate',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.last_after_order_survey_response_avg_rating': {
        display_name: 'Last After Order Survey Response Avg Rating',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.last_after_order_survey_response_score': {
        display_name: 'Last After Order Survey Response Score',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.last_after_order_survey_response_timestamp': {
        display_name: 'Last After Order Survey Response Timestamp',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'time',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.last_order_timestamp': {
        display_name: 'Last Order Timestamp',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'time',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.median_order_delivery_time_last_4_weeks': {
        display_name: 'Median Order Delivery Time L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.night_hour_order_rate': {
        display_name: 'Night Hour Order Rate',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.non_restaurants_vertical_order_rate': {
        display_name: 'Non Restaurants Vertical Order Rate',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.non_restaurants_vertical_order_rate_last_4_weeks': {
        display_name: 'Non-Restaurants Vertical Order Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.offer_order_rate_last_4_weeks': {
        display_name: 'Offer Order Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.online_payment_order_rate_last_4_weeks': {
        display_name: 'Online Payment Order Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.order_fail_rate_last_4_weeks': {
        display_name: 'Order Fail Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.orders_last_12_weeks': {
        display_name: 'Orders L12W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.orders_last_4_weeks': {
        display_name: 'Orders L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.peak_hour_order_rate': {
        display_name: 'Peak Hour Order Rate',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.preferred_cuisine_rate_last_4_weeks': {
        display_name: 'Preferred Cuisine Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.preferred_cuisine_type_last_4_weeks': {
        display_name: 'Preferred Cuisine Type L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.total_orders': {
        display_name: 'Total Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.unique_addresses_used_last_4_weeks': {
        display_name: 'Unique Addresses Used L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.unique_ordered_last_12_weeks': {
        display_name: 'Unique Ordered L12W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.unique_ordered_weeks': {
        display_name: 'Unique Ordered Weeks',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.unique_vendors_ordered_last_4_weeks': {
        display_name: 'Unique Vendors Ordered L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.voucher_order_rate_last_4_weeks': {
        display_name: 'Voucher Order Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
      'qubik.order_attributes.weekend_order_rate': {
        display_name: 'Weekend Order Rate',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Order Attributes',
      },
    },
  },
  {
    name: 'Pandata',
    rules: {
      'pandata.ab_test_group': {
        display_name: 'AB Test Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.average_order_value_all_time': {
        display_name: 'Average Order Value',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.average_order_value_group_all_time': {
        display_name: 'Average Order Value Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.average_order_value_group_recent': {
        display_name: 'Average Order Value Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.average_order_value_recent': {
        display_name: 'Average Order Value Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_days_to_subsequent_order_all_time': {
        display_name: 'Average Days to Subsequent Order',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_days_to_subsequent_order_recent': {
        display_name: 'Average Days to Subsequent Order Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_delivery_fee_all_time': {
        display_name: 'Average Delivery Fee',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_delivery_fee_recent': {
        display_name: 'Average Delivery Fee Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_delivery_seconds_all_time': {
        display_name: 'Average Delivery (Seconds)',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_delivery_seconds_recent': {
        display_name: 'Average Delivery Recent (Seconds) ',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_item_per_order_all_time': {
        display_name: 'Average Item Per Order',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_item_per_order_recent': {
        display_name: 'Average Item Per Order Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_order_delay_all_time': {
        display_name: 'Average Order Delay',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.avg_order_delay_recent': {
        display_name: 'Average Order Delay Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.business_verticals_order_placed_all_time': {
        display_name: 'Business Vertical Orders Placed',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.business_verticals_order_placed_recent': {
        display_name: 'Business Vertical Orders Placed Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.city_with_last_order': {
        display_name: 'City With Last Order',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_actual_amount_spent_distribution_all_time': {
        display_name: 'Customer Actual Amount Spent Distribution',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.customer_actual_amount_spent_distribution_recent': {
        display_name: 'Customer Actual Amount Spent Distribution Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.customer_incentive_value_distribution_all_time': {
        display_name: 'Customer Incentive Value Distribution',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.customer_incentive_value_distribution_recent': {
        display_name: 'Customer Incentive Value Distribution Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.customer_sessions_all_time': {
        display_name: 'Maximum Order Value',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_sessions_recent': {
        display_name: 'Average Order Value Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_sessions_with_orders_all_time': {
        display_name: 'Customer Sessions With Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_sessions_with_orders_recent': {
        display_name: 'Customer Sessions With Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_total_actual_amount_spent_all_time': {
        display_name: 'Customer Total Actual Amount Spent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_total_actual_amount_spent_recent': {
        display_name: 'Customer Total Actual Amount Spent Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_total_gmv_value_all_time': {
        display_name: 'Customer Total GMV Value',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_total_gmv_value_recent': {
        display_name: 'Customer Total GMV Value Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_total_incentives_used_all_time': {
        display_name: 'Customer Total Incentives Used',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.customer_total_incentives_used_recent': {
        display_name: 'Customer Total Incentives Used Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.days_since_first_transaction': {
        display_name: 'Days Since First Transaction',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.days_since_last_transaction': {
        display_name: 'Days Since Last Transaction',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.days_since_signup': {
        display_name: 'Days Since Signup',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.discounted_orders_all_time': {
        display_name: 'Discounted Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.discounted_orders_recent': {
        display_name: 'Discounted Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.first_transaction_date_local': {
        display_name: 'First Transaction Date (Local) ',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'time',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_cuisine_all_time': {
        display_name: 'Frequent Cuisine',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_cuisine_recent': {
        display_name: 'Frequent Cuisine Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_order_hour_all_time': {
        display_name: 'Frequent Order Hour',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_order_hour_recent': {
        display_name: 'Frequent Order Hour Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_vendor_chain_code_all_time': {
        display_name: 'Frequent Vendor Chain Code',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_vendor_chain_code_recent': {
        display_name: 'Frequent Vendor Chain Code Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_vendor_chain_name_all_time': {
        display_name: 'Frequent Vendor Chain Name',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_vendor_chain_name_recent': {
        display_name: 'Frequent Vendor Chain Name Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_vendor_code_all_time': {
        display_name: 'Frequent Vendor Code',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_vendor_code_recent': {
        display_name: 'Frequent Vendor Code Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_vertical_all_time': {
        display_name: 'Frequent Vertical',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.frequent_vertical_recent': {
        display_name: 'Frequent Vertical Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.highest_gfv_cuisine_all_time': {
        display_name: 'Highest GFV Cuisine',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.highest_gfv_cuisine_recent': {
        display_name: 'Highest GFV Cuisine Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.incentive_sensitivity_group_all_time': {
        display_name: 'Incentive Sensitivity Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.incentive_sensitivity_group_recent': {
        display_name: 'Incentive Sensitivity Group Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.incentive_value_sensitivity_group_all_time': {
        display_name: 'Incentive Value Sensitivity Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.incentive_value_sensitivity_group_recent': {
        display_name: 'Incentive Value Sensitivity Group Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.incentivised_orders_all_time': {
        display_name: 'Incentivised Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.incentivised_orders_recent': {
        display_name: 'Incentivised Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.is_churned_subscription_user': {
        display_name: 'Is Churned Subscription User',
        supported_comparator: ['=', '!='],
        supported_type: 'bool',
        values: [],
        section: 'Pandata',
      },
      'pandata.is_dormant': {
        display_name: 'Is Dormant',
        supported_comparator: ['=', '!='],
        supported_type: 'bool',
        values: [],
        section: 'Pandata',
      },
      'pandata.is_subscription_user': {
        display_name: 'Is Subscription User',
        supported_comparator: ['=', '!='],
        supported_type: 'bool',
        values: [],
        section: 'Pandata',
      },
      'pandata.latest_transaction_date_local': {
        display_name: 'Latest Transaction Date (Local)',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'time',
        values: [],
        section: 'Pandata',
      },
      'pandata.lg_city_with_last_order': {
        display_name: 'LG City With Last Order',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.maximum_order_value_all_time': {
        display_name: 'Maximum Order Value',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.maximum_order_value_recent': {
        display_name: 'Average Order Value Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.minimum_order_value_all_time': {
        display_name: 'Minimum Order Value',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.minimum_order_value_recent': {
        display_name: 'Minimum Order Value Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.order_elasticity_score': {
        display_name: 'Order Elasticity Score',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.order_freq_distribution_all_time': {
        display_name: 'Order Frequency Distribution',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.order_freq_distribution_recent': {
        display_name: 'Order Frequency Distribution Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.order_frequency_group_all_time': {
        display_name: 'Order Frequency Group',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.order_frequency_group_recent': {
        display_name: 'Order Frequency Group Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_challenge_orders_all_time': {
        display_name: 'Percent Challenged Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_challenge_orders_recent': {
        display_name: 'Percent Challenged Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_delivery_fee_orders_all_time': {
        display_name: 'Percent Delivery Fee Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_delivery_fee_orders_recent': {
        display_name: 'Percent Delivery Fee Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_discounted_orders_all_time': {
        display_name: 'Percent Discount Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_discounted_orders_recent': {
        display_name: 'Percent Discount Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_incentivised_orders_all_time': {
        display_name: 'Percent Incentivised Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_incentivised_orders_recent': {
        display_name: 'Percent Incentivised Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_vouchered_orders_all_time': {
        display_name: 'Percent Vouchered Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.percent_vouchered_orders_recent': {
        display_name: 'Percent Vouchered Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Pandata',
      },
      'pandata.retention_score': {
        display_name: 'Retention Score',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.signed_up_date_local': {
        display_name: 'Signed Up Date Local',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Pandata',
      },
      'pandata.spending_power_sensitivity_group_all_time': {
        display_name: 'Spending Power Sensitivity Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.spending_power_sensitivity_group_recent': {
        display_name: 'Spending Power Sensitivity Group Recent',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_challenge_orders_all_time': {
        display_name: 'Total Challenge Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_challenge_orders_recent': {
        display_name: 'Total Challenge Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_cities_with_orders_all_time': {
        display_name: 'Total Cities With Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_cities_with_orders_recent': {
        display_name: 'Total Cities With Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_concepts_orders_all_time': {
        display_name: 'Total Concept Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_concepts_orders_recent': {
        display_name: 'Total Concept Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_dmart_orders_all_time': {
        display_name: 'Total DMart Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_dmart_orders_recent': {
        display_name: 'Total DMart Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_kitchen_orders_all_time': {
        display_name: 'Total Kitchen Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_kitchen_orders_recent': {
        display_name: 'Total Kitchen Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_orders_all_time': {
        display_name: 'Total Order All Time',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_orders_recent': {
        display_name: 'Signed Up Date Local',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'time',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_restaurant_orders_all_time': {
        display_name: 'Total Restaurant Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_restaurant_orders_recent': {
        display_name: 'Total Restaurant Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_shop_orders_all_time': {
        display_name: 'Total Shop Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_shop_orders_recent': {
        display_name: 'Total Shop Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_vendor_chains_all_time': {
        display_name: 'Total Vendor Chains',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.total_vendor_chains_recent': {
        display_name: 'Total Vendor Chains Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.vouchered_orders_all_time': {
        display_name: 'Vouchered Orders',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
      'pandata.vouchered_orders_recent': {
        display_name: 'Vouchered Orders Recent',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Pandata',
      },
    },
  },
  {
    name: 'Predictions',
    rules: {
      'qubik.predictions.churn.churn_group': {
        display_name: 'Churn Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Predictions',
      },
      'qubik.predictions.churn.churn_probability': {
        display_name: 'Churn Probability',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Predictions',
      },
    },
  },
  {
    name: 'Segment',
    rules: {
      'qubik.segment.activity.group': {
        display_name: 'Activity',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [
          { name: 'A', value: 'a' },
          { name: 'B', value: 'b' },
          { name: 'C', value: 'c' },
          { name: 'D', value: 'd' },
          { name: 'E', value: 'e' },
          { name: 'F', value: 'f' },
          { name: 'G', value: 'g' },
          { name: 'H', value: 'h' },
          { name: 'I', value: 'i' },
          { name: 'J', value: 'j' },
          { name: 'K', value: 'k' },
          { name: 'L', value: 'l' },
          { name: 'M', value: 'm' },
          { name: 'N', value: 'n' },
          { name: 'O', value: 'o' },
          { name: 'P', value: 'p' },
          { name: 'Q', value: 'q' },
          { name: 'R', value: 'r' },
          { name: 'S', value: 's' },
          { name: 'T', value: 't' },
          { name: 'U', value: 'u' },
          { name: 'V', value: 'v' },
          { name: 'W', value: 'w' },
          { name: 'X', value: 'x' },
          { name: 'Y', value: 'y' },
          { name: 'Z', value: 'z' },
        ],
        section: 'Segment',
      },
      'qubik.segment.customer_experience.group': {
        display_name: 'Customer Experience Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [
          { name: 'A', value: 'a' },
          { name: 'B', value: 'b' },
          { name: 'C', value: 'c' },
          { name: 'D', value: 'd' },
          { name: 'E', value: 'e' },
          { name: 'F', value: 'f' },
          { name: 'G', value: 'g' },
          { name: 'H', value: 'h' },
          { name: 'I', value: 'i' },
          { name: 'J', value: 'j' },
          { name: 'K', value: 'k' },
          { name: 'L', value: 'l' },
          { name: 'M', value: 'm' },
          { name: 'N', value: 'n' },
          { name: 'O', value: 'o' },
          { name: 'P', value: 'p' },
          { name: 'Q', value: 'q' },
          { name: 'R', value: 'r' },
          { name: 'S', value: 's' },
          { name: 'T', value: 't' },
          { name: 'U', value: 'u' },
          { name: 'V', value: 'v' },
          { name: 'W', value: 'w' },
          { name: 'X', value: 'x' },
          { name: 'Y', value: 'y' },
          { name: 'Z', value: 'z' },
        ],
        section: 'Segment',
      },
      'qubik.segment.customer_experience.score': {
        display_name: 'Customer Experience Score',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Segment',
      },
      'qubik.segment.engagement.group': {
        display_name: 'Engagement Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [
          { name: 'A', value: 'a' },
          { name: 'B', value: 'b' },
          { name: 'C', value: 'c' },
          { name: 'D', value: 'd' },
          { name: 'E', value: 'e' },
          { name: 'F', value: 'f' },
          { name: 'G', value: 'g' },
          { name: 'H', value: 'h' },
          { name: 'I', value: 'i' },
          { name: 'J', value: 'j' },
          { name: 'K', value: 'k' },
          { name: 'L', value: 'l' },
          { name: 'M', value: 'm' },
          { name: 'N', value: 'n' },
          { name: 'O', value: 'o' },
          { name: 'P', value: 'p' },
          { name: 'Q', value: 'q' },
          { name: 'R', value: 'r' },
          { name: 'S', value: 's' },
          { name: 'T', value: 't' },
          { name: 'U', value: 'u' },
          { name: 'V', value: 'v' },
          { name: 'W', value: 'w' },
          { name: 'X', value: 'x' },
          { name: 'Y', value: 'y' },
          { name: 'Z', value: 'z' },
        ],
        section: 'Segment',
      },
      'qubik.segment.engagement.score': {
        display_name: 'Engagement Score',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Segment',
      },
      'qubik.segment.engagement.unique_interactions_last_4_weeks': {
        display_name: 'Engagement Unique Interactions L4W',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [
          { name: 'A', value: 'a' },
          { name: 'B', value: 'b' },
          { name: 'C', value: 'c' },
          { name: 'D', value: 'd' },
          { name: 'E', value: 'e' },
          { name: 'F', value: 'f' },
          { name: 'G', value: 'g' },
          { name: 'H', value: 'h' },
          { name: 'I', value: 'i' },
          { name: 'J', value: 'j' },
          { name: 'K', value: 'k' },
          { name: 'L', value: 'l' },
          { name: 'M', value: 'm' },
          { name: 'N', value: 'n' },
          { name: 'O', value: 'o' },
          { name: 'P', value: 'p' },
          { name: 'Q', value: 'q' },
          { name: 'R', value: 'r' },
          { name: 'S', value: 's' },
          { name: 'T', value: 't' },
          { name: 'U', value: 'u' },
          { name: 'V', value: 'v' },
          { name: 'W', value: 'w' },
          { name: 'X', value: 'x' },
          { name: 'Y', value: 'y' },
          { name: 'Z', value: 'z' },
        ],
        section: 'Segment',
      },
      'qubik.segment.intention.group': {
        display_name: 'Intention Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [
          { name: 'A', value: 'a' },
          { name: 'B', value: 'b' },
          { name: 'C', value: 'c' },
          { name: 'D', value: 'd' },
          { name: 'E', value: 'e' },
          { name: 'F', value: 'f' },
          { name: 'G', value: 'g' },
          { name: 'H', value: 'h' },
          { name: 'I', value: 'i' },
          { name: 'J', value: 'j' },
          { name: 'K', value: 'k' },
          { name: 'L', value: 'l' },
          { name: 'M', value: 'm' },
          { name: 'N', value: 'n' },
          { name: 'O', value: 'o' },
          { name: 'P', value: 'p' },
          { name: 'Q', value: 'q' },
          { name: 'R', value: 'r' },
          { name: 'S', value: 's' },
          { name: 'T', value: 't' },
          { name: 'U', value: 'u' },
          { name: 'V', value: 'v' },
          { name: 'W', value: 'w' },
          { name: 'X', value: 'x' },
          { name: 'Y', value: 'y' },
          { name: 'Z', value: 'z' },
        ],
        section: 'Segment',
      },
      'qubik.segment.intention.score': {
        display_name: 'Intention Score',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Segment',
      },
      'qubik.segment.vendor_selection.group': {
        display_name: 'Vendor Selection Group',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [
          { name: 'A', value: 'a' },
          { name: 'B', value: 'b' },
          { name: 'C', value: 'c' },
          { name: 'D', value: 'd' },
          { name: 'E', value: 'e' },
          { name: 'F', value: 'f' },
          { name: 'G', value: 'g' },
          { name: 'H', value: 'h' },
          { name: 'I', value: 'i' },
          { name: 'J', value: 'j' },
          { name: 'K', value: 'k' },
          { name: 'L', value: 'l' },
          { name: 'M', value: 'm' },
          { name: 'N', value: 'n' },
          { name: 'O', value: 'o' },
          { name: 'P', value: 'p' },
          { name: 'Q', value: 'q' },
          { name: 'R', value: 'r' },
          { name: 'S', value: 's' },
          { name: 'T', value: 't' },
          { name: 'U', value: 'u' },
          { name: 'V', value: 'v' },
          { name: 'W', value: 'w' },
          { name: 'X', value: 'x' },
          { name: 'Y', value: 'y' },
          { name: 'Z', value: 'z' },
        ],
        section: 'Segment',
      },
    },
  },
  {
    name: 'Visit Attributes',
    rules: {
      'qubik.visit_attributes.abandoned_cart_rate_last_4_weeks': {
        display_name: 'Abandoned Cart Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.acquisition_funnel': {
        display_name: 'Acquisition Funnel',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.avg_interaction_speed_last_4_weeks': {
        display_name: 'Average Interaction Speed L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.avg_unique_vendors_available_last_4_weeks': {
        display_name: 'Average Unique Vendors Available L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.avg_vendors_open_last_4_weeks': {
        display_name: 'Average Vendors Open L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.close_vendor_rate_last_4_weeks': {
        display_name: 'Close Vendor Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.first_platform_device': {
        display_name: 'First Platform Device',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.first_visit_channel': {
        display_name: 'First Visit Channel',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.last_platform_device': {
        display_name: 'Last Platform Device',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.last_visit_channel': {
        display_name: 'Last Visit chanel',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.last_visit_timestamp': {
        display_name: 'Last Visited Timestamp',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'time',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.non_restaurants_vertical_visit_rate_last_4_weeks': {
        display_name: 'Non Restaurant Vertical Visit Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.search_fail_rate_last_4_weeks': {
        display_name: 'Search Fail Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.session_duration_last_4_weeks': {
        display_name: 'Session Duration L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.total_visit': {
        display_name: 'Total Visits',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.unique_addresses_used_last_4_weeks': {
        display_name: 'Unique Addresses Used L12W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.unique_platform_device_last_12_weeks': {
        display_name: 'Unique Platform Device L12W',
        supported_comparator: ['=', '!=', 'in'],
        supported_type: 'string',
        values: [
          { name: 'Android', value: 'Android' },
          { name: 'iOS', value: 'iOS' },
          { name: 'Web', value: 'Web' },
          { name: 'Mobile Web', value: 'mWeb' },
        ],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.unique_vendors_viewed_last_4_weeks': {
        display_name: 'Unique Vendors Viewed L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.visits_last_12_weeks': {
        display_name: 'Visit L12W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.visits_last_4_weeks': {
        display_name: 'Visit L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'int',
        values: [],
        section: 'Visit Attributes',
      },
      'qubik.visit_attributes.voucher_error_rate_last_4_weeks': {
        display_name: 'Voucher Error Rate L4W',
        supported_comparator: ['>', '<', '>=', '<=', '=', '!=', 'in'],
        supported_type: 'float',
        values: [
          { name: 'min', value: '0' },
          { name: 'max', value: '1' },
        ],
        section: 'Visit Attributes',
      },
    },
  },
];
